### ISSUE TITLE
Labeling the fire

### ISSUE THREAD

**Issue by AlaaSerhal** [arpit-jadon/FireNet-LightWeight-Network-for-Fire-Detection#2]
Can this project be edited so that we can have a bounding box around the fire? I want to detect exactly the fire in the frame captured. Can you please provide with the steps to take or the functions to use. I checked on the internet but it seems that there are files that missing. Looking forward to your answer, thank you in advance.

**Comment by arvinnick** [comment]
[real_time_detection.txt](https://github.com/arpit-jadon/FireNet-LightWeight-Network-for-Fire-Detection/files/4022340/real_time_detection.txt)
I have added it. Change "txt" to "py". I'm not an author of this repo. I don't know how to push a change. If the prob > 50, then "fire" will be shown. otherwise "nofire".

**Comment by AlaaSerhal** [comment]
Thank you. However, this is not what I exactly mean. What I mean is that I need to have a contour or a bounding box surrounding the exact location of the fire in the picture not just simply showing if there is fire or no.

**Comment by arvinnick** [comment]
Oh, I don't think you find localization in this repo.

**Comment by arpit-jadon** [comment]
Hi! @AlaaSerhal, the codes in the repo, at this point in time are capable of classification. I am working on the localization part as well, will let you know once I upload the relevant codes.
